### ISSUE TITLE
Boi

### ISSUE THREAD

**Issue by ghost** [CosignCosine/cosigncosine.github.io#2]
Your website should have a trigger warning.

**Comment by CosignCosine** [comment]
no

**Comment by CosignCosine** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/c0871c38-0c27-4ae4-9196-389fa986867a-ad92fc1f-08cb-455d-9740-75e2354b629b-v1.png?transparent=1&palette=1&width=246)
